#!/bin/bash
echo "Applying symlink configuration..."
ln -s "../../apply.symlink-config.sh" "selected/root/apply.symlink-config.sh"
ln -s "../../package.json" "selected/root/package.json"
ln -s "../../README.md" "selected/root/README.md"
ln -s "../../symlink-config.code-workspace" "selected/root/symlink-config.code-workspace"
ln -s "../../.gitignore" "selected/root/_gitignore"
ln -s "../../tsconfig.json" "selected/root/tsconfig.json"
ln -s "../../src/main.ts" "selected/src/main.ts"
ln -s "../../test-ws-unix/.vscode/settings.json" "selected/test-workspace/vscode_-_settings.json"
