import { FILE_NAMES } from './files'
import { SETTINGS } from './settings'

export const WATCHERS = {
  SYMLINK_CONFIG_SETTINGS: SETTINGS.SYMLINK_CONFIG.SECTION,
  FILES_SETTINGS: SETTINGS.FILES.SECTION,
  GITIGNORE: FILE_NAMES.GITIGNORE,
  NEXT_SYMLINK_CONFIG: FILE_NAMES.NEXT_SYMLINK_CONFIG,
  CURRENT_SYMLINK_CONFIG: FILE_NAMES.CURRENT_SYMLINK_CONFIG,
  SYMLINK_CONFIGS: FILE_NAMES.SYMLINK_CONFIG,
  SYMLINKS: 'handled symlinks',
} as const
